version: echo local help on unknown arg

diff --git a/_gh-release/version b/_gh-release/version
--- a/_gh-release/version
+++ b/_gh-release/version
@@ -35,7 +35,7 @@ while read option; do
         -m|--message) read message; messageSpecified=1;;
         -h|--help) info.versionHelp; exit;;
         '') continue;;
-        *) echo "${underline}${lightred}Error$reset${lightred}: Unknown option $option$reset"; info.usage; exit 2; ;;
+        *) echo "${underline}${lightred}Error$reset${lightred}: Unknown option $option$reset"; info.versionHelp; exit 2; ;;
     esac
 done <<< $(for i in "$@"; do echo "$i"; done);
 
